source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '13.0'

target 'ZLStackView_Example' do
  pod 'ZLStackView', :path => '../'
  pod 'Masonry'
  pod 'SnapKit'
  pod 'Then'

  target 'ZLStackView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
